name: Build-Test-Pack

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - name: Create Environment File for Output
        run: echo "newVersion=1.0.${{github.run_number}}" >> $GITHUB_ENV

      - name: Update .csproj Version
        run: |
          # Update the version in the .csproj file
          sed -i 's/<Version>.*<\/Version>/<Version>${{ env.newVersion }}<\/Version>/' AJL/AJL.csproj
        working-directory: src
        
      - name: Update .nuspec Version
        run: |
          # Update the version in the .csproj file
          sed -i 's/<version>.*<\/version>/<version>${{ env.newVersion }}<\/version>/' AJL/AnotherJsonLib.nuspec
        working-directory: src
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x  # Adjust to your project's .NET version

      - name: Restore dependencies
        run: dotnet restore AJL/AJL.csproj
        working-directory: src  # Set the working directory to 'src'

      - name: Build
        run: dotnet build AJL/AJL.csproj --configuration Release --no-restore
        working-directory: src  # Set the working directory to 'src'
        
      - name: unit tests for Another Json Lib
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: tests/AJL.Tests
          report_name: another_json_lib_tests
          report_title: Another Json Lib Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: another_json_lib_tests.md
          gist_badge_label: 'Unit Tests: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}

      - name: Pack & Publish nuget   
        run: |
          dotnet pack AJL/AJL.csproj --no-dependencies --configuration Release /p:NuspecFile=AnotherJsonLib.nuspec --output ../.artifacts/
          cd ../.artifacts/ | pwd
          dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
        shell: bash
        working-directory: src
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AnotherJsonLibrary.${{ env.newVersion }}.nupkg
          path: .artifacts/*.nupkg

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: .artifacts/*.nupkg
          tag_name: ${{ env.newVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

