name: Build-Test-Pack

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - name: Create Environment File for Output
        run: echo "newVersion=1.0.1" >> $GITHUB_ENV

      - name: Increment Version
        id: increment_version
        run: |
          # Your version increment logic here
          # Example: Update version in .csproj
          csprojPath="src/AJL/AJL.csproj"
          currentVersion=$(xmllint --xpath 'string(/Project/PropertyGroup/Version)' $csprojPath)

          # Extract the version and version suffix
          IFS='-' read -ra versionParts <<< "$currentVersion"
          version=${versionParts[0]}
          versionSuffix=${versionParts[1]}

          # Increment the version
          IFS='.' read -ra versionArray <<< "$version"
          major=${versionArray[0]}
          minor=${versionArray[1]}
          patch=${versionArray[2]}

          # Increment the patch version
          patch=$((patch + 1))

          # Create the new version string without hyphen
          newVersion="$major.$minor.$patch-${{github.run_number}}"
          
          # Update the version in the .csproj
          sed -i "s/<Version>.*<\/Version>/<Version>$newVersion<\/Version>/" $csprojPath
          
          echo "::set-output name=version::$newVersion"

        shell: bash

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x  # Adjust to your project's .NET version

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src  # Set the working directory to 'src'

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src  # Set the working directory to 'src'

      - name: Test
        run: dotnet test --configuration Release --no-restore
        working-directory: tests/AJL.Tests  # Set the working directory to 'tests/AJL.Tests'

      - name: Pack
        run: dotnet pack --configuration release
        working-directory: src  # Set the working directory to 'src'

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: src/AJL/bin/Release/*.nupkg



