name: Build-Test-Pack

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - name: Create Environment File for Output
        run: echo "newVersion=1.0.1" >> $GITHUB_ENV

      - name: Increment Version
        id: increment_version
        run: |
          # Set the version with GitHub run number
          newVersion="1.0.${{github.run_number}}"
          
          # Update the version in the .csproj
          csprojPath="src/AJL/AJL.csproj"
          sed -i "s/<Version>.*<\/Version>/<Version>$newVersion<\/Version>/" $csprojPath
          
          # Set the output variable for later steps
          echo "::set-output name=version::$newVersion"
      
        shell: bash

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x  # Adjust to your project's .NET version

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src  # Set the working directory to 'src'

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src  # Set the working directory to 'src'

      - name: Test
        run: dotnet test --configuration Release --no-restore
        working-directory: tests/AJL.Tests  # Set the working directory to 'tests/AJL.Tests'

      - name: Pack
        run: dotnet pack --configuration release --output ./../.artifacts/
        working-directory: src  # Set the working directory to 'src'

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AnotherJsonLibrary.${{ steps.increment_version.outputs.version }}.nupkg
          path: .artifacts/*.nupkg

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: .artifacts/*.nupkg
          tag_name: ${{ steps.increment_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

