name: Build, Pack, and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - name: Create Environment File for Output
        run: echo "newVersion=1.0.1" >> $GITHUB_ENV

      - name: Increment Version
        id: increment_version
        run: |
          # Your version increment logic here
          # Example: Update version in .csproj
          csprojPath="src/AJL/AJL.csproj"
          currentVersion=$(xmllint --xpath 'string(/Project/PropertyGroup/Version)' $csprojPath)
          # Increment version logic here...
          newVersion="1.0.1"
          # Update the version in the .csproj
          sed -i "s/<Version>.*<\/Version>/<Version>$newVersion<\/Version>/" $csprojPath
          echo "::set-output name=version::$newVersion"
        shell: bash

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x  # Adjust to your project's .NET version

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src  # Set the working directory to 'src'

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src  # Set the working directory to 'src'

      - name: Test
        run: dotnet test --configuration Release --no-restore
        working-directory: tests/AJL.Tests  # Set the working directory to 'tests/AJL.Tests'

      - name: Pack
        run: dotnet pack AJL/AJL.csproj -p:NuspecFile=AJL/AnotherJsonLibrary.nuspec -p:NuspecBasePath=AJL/nuget
        working-directory: src  # Set the working directory to 'src'

      - name: List Files and Subdirectories
        run: |
          # Use the 'find' command to list all files and subdirectories
          find "${GITHUB_WORKSPACE}" -type f -print
          find "${GITHUB_WORKSPACE}" -type d -print
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./src/AJL/*.nupkg
          tag_name: 1.0.1  # Use the desired version directly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

