name: Build and Test PRs

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x  

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src  

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x 

      - name: Build
        run: dotnet build AnotherJsonLib/AnotherJsonLib.csproj --configuration Release
        working-directory: src  # Set the working directory to 'src'

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
        working-directory: test/AnotherJsonLib.Tests  # Set the working directory to 'test'

