name: Main Branch CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x  # Adjust to your project's .NET version

      - name: Set working directory
        run: cd src  # Change to the 'src' directory where your project is located

      - name: List files in current directory
        run: ls

      - name: Print current directory
        run: pwd

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build src/AnotherJsonLib.sln --configuration Release --no-restore
        
      - name: Test
        run: dotnet test src/AJL.Tests/AJL.Tests.csproj --configuration Release --no-build --verbosity normal
