name: Main Branch CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x  # Adjust to your project's .NET version

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src  # Set the working directory to 'src'

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src  # Set the working directory to 'src'
        
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
        working-directory: src  # Set the working directory to 'src'
