name: Publish NuGet Package

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: AnotherJsonLibrary.${{ steps.get_latest_release.outputs.release_tag }}.nupkg # Specify the artifact name
          path: src/AJL/bin/Release

      - name: Publish NuGet package
        run: dotnet nuget push src/AJL/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
        working-directory: ./src/AJL/bin/Release
