name: Publish NuGet Package

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the latest release tag
        id: get_latest_release
        run: echo ::set-output name=release_tag::${{ github.event.release.tag_name }}

      - name: Determine package path
        id: determine_package_path
        run: echo ::set-output name=package_path::"src/AJL/bin/Release/AnotherJsonLibrary.${{ steps.get_latest_release.outputs.release_tag }}.nupkg"

      - name: Publish NuGet package
        run: dotnet nuget push ${{ steps.determine_package_path.outputs.package_path }} --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
