name: Publish NuGet Package

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the release tag
        id: get_release_tag
        run: echo ::set-output name=release_tag::${{ github.event.release.tag_name }}

      - name: Create Environment File for Output
        run: echo "release_tag=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.2.1
        with:
          workflow: build-test.yml
          workflow_conclusion: success
          name: AnotherJsonLibrary.${{ github.event.release.tag_name }}.nupkg
  
         
      - name: Get artifact path
        id: get_artifact_path
        run: |
          artifact_path=$(find "$GITHUB_WORKSPACE/artifacts" -maxdepth 1 -type f -name '*.nupkg')
          echo "artifact_path=${artifact_path}" >> $GITHUB_OUTPUT
          echo "Found artifact: ${artifact_path}"

      - name: Publish NuGet package
        run: dotnet nuget push "${{ steps.get_artifact_path.outputs.artifact_path }}" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
