name: Publish NuGet Package

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the release tag
        id: get_release_tag
        run: echo ::set-output name=release_tag::${{ github.event.release.tag_name }}

      - name: Create Environment File for Output
        run: echo "release_tag=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        
      - name: Update .nuspec Version
        run: |
          # Update the version in the .nuspec file
          nuspecPath="src/AJL/AnotherJsonLib.nuspec"
          sed -i "s|<version>.*<\/version>|<version>${{ env.release_tag }}<\/version>|" $nuspecPath
        shell: bash


      - name: Download artifact
        uses: aochmann/actions-download-artifact@1.0.4
        with:
          workflow: build-test.yml
          workflow_conclusion: success
          # GitHub token
          github_token: ${{ secrets.RELEASE_TOKEN }}
          # Repository name with owner
          latest: true
          name_is_regexp: false
          name: AnotherJsonLibrary.${{ github.event.release.tag_name }}.nupkg
          check_artifacts: true
          search_artifacts: true
          if_no_artifact_found: fail
          path: ./.artifacts/

      - name: Publish NuGet package
        run: dotnet nuget push .artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
