name: Publish NuGet Package

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the release tag
        id: get_release_tag
        run: echo ::set-output name=release_tag::${{ github.event.release.tag_name }}

      - name: List Artifacts
        run: ls -al $GITHUB_WORKSPACE
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    
      - name: Download artifact
        uses: aochmann/actions-download-artifact@1.0.4
        with:
          # GitHub token
          github_token: ${{ secrets.RELEASE_TOKEN }}
          # Repository name with owner
          latest: true
          # Artifact unpack location
          path: ./.artifacts/

      - name: Publish NuGet package
        run: dotnet nuget push .artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
