name: Publish NuGet Package

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the release tag
        id: get_release_tag
        run: echo ::set-output name=release_tag::${{ github.event.release.tag_name }}

      - name: Create Environment File for Output
        run: echo "release_tag=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4

      - name: Publish NuGet package
        run: dotnet nuget push  .artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
