name: Publish NuGet Package

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the release tag
        id: get_release_tag
        run: echo ::set-output name=release_tag::${{ github.event.release.tag_name }}

      - name: Download artifact
        uses: aochmann/actions-download-artifact@1.0.4
        with:
          workflow: build-test.yml
          workflow_conclusion: success
          # GitHub token
          github_token: ${{ secrets.RELEASE_TOKEN }}
          # Repository name with owner
          latest: true
          name_is_regexp: false
          name: AnotherJsonLibrary.${{ github.event.release.tag_name }}.nupkg
          check_artifacts: true
          search_artifacts: true
          if_no_artifact_found: fail
          path: ./.artifacts/

      - name: List root
        run: ls -al $GITHUB_WORKSPACE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: List artifact
        run: ls -al ./.artifacts/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
        
      - name: Update NuGet package version
        id: update_nuspec_version
        run: |
          sed -i "s/<version>.*<\/version>/<version>${{ steps.get_release_tag.outputs.release_tag }}<\/version>/" AnotherJsonLibrary.nuspec
        working-directory: ./.artifacts/

      - name: Publish NuGet package
        run: dotnet nuget push .artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
